// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpjj7FQ5qvfMWGY5LUg7mi75Ea9_QbFA8',
    appId: '1:196099255366:web:3f1ad640102fb6e430ae47',
    messagingSenderId: '196099255366',
    projectId: 'marriagecatalogvg',
    authDomain: 'marriagecatalogvg.firebaseapp.com',
    storageBucket: 'marriagecatalogvg.appspot.com',
    measurementId: 'G-EXDY4X370J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbkXUu6IYhULwewF8ZpsjEaSclnEHU9PQ',
    appId: '1:196099255366:android:dcd301f5600ba74330ae47',
    messagingSenderId: '196099255366',
    projectId: 'marriagecatalogvg',
    storageBucket: 'marriagecatalogvg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCggb_NgfVM7gU7ZThNB6Zy_2syrkZvzQU',
    appId: '1:196099255366:ios:d260ad7e1d3893cc30ae47',
    messagingSenderId: '196099255366',
    projectId: 'marriagecatalogvg',
    storageBucket: 'marriagecatalogvg.appspot.com',
    iosClientId: '196099255366-kk6f7chniifscr6h45fl82juqfcu46ek.apps.googleusercontent.com',
    iosBundleId: 'com.example.marriageCatalog',
  );
}
